name: Java CI with Gradle

on:[push]

jobs:
  build:

    runs-on: ubuntu-latest
	  
	  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
       arguments: build
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: eureka-server
        path: C:\Users\hp\Desktop\Eureka\Eureka-serer
